### ISSUE TITLE
Cannot build OpenGeode with GCC 4.8.5

### ISSUE THREAD

**Issue by yo35** [Geode-solutions/OpenGeode#779]
When compiling OpenGeode with GCC 4.8.5, I get the following error:

```
[ 46%] Building CXX object src/geode/model/CMakeFiles/model.dir/helpers/model_coordinate_reference_system.cpp.o
...
/usr/include/c++/4.8.2/ext/new_allocator.h:120:4: error: no matching function for call to
‘std::pair<geode::NamedType<std::basic_string<char>, geode::CRSTag>, std::basic_string<char>
>::pair(geode::NamedType<std::basic_string<char>, geode::CRSTag>, absl::string_view)’
```

I've observed this error with the following versions of OpenGeode:
- v14.3.3
- v14.1.9
(I haven't tried other versions of OpenGeode)

**Comment by BotellaA** [comment]
Hello @yo35,
Could you provide the complete error log, please?

**Comment by BotellaA** [comment]
I think it has been fixed on the `next` branch with this change https://github.com/Geode-solutions/OpenGeode/commit/d97afccfcbe0fbab5f44555917175fddb862600a

**Comment by yo35** [comment]
Here is the complete log:
[error-build-opengeode.txt](https://github.com/Geode-solutions/OpenGeode/files/11907166/error-build-opengeode.txt)

**Comment by yo35** [comment]
@BotellaA Thanks for your quick reply. Indeed, applying change https://github.com/Geode-solutions/OpenGeode/commit/d97afccfcbe0fbab5f44555917175fddb862600a fixes the issue. I've been able to build OpenGeode v14.1.9 + this patch with the dated GCC 4.8.5.
